### ISSUE TITLE
com.toshiba.mwcloud.gs.common.GSStatementException: [1007:CM_NOT_SUPPORTED] not support Row Expiration

### ISSUE THREAD

**Issue by tom055** [griddb/griddb#399]
An error occurred when I wanted to create a time series expiration
```jsx
    ContainerInfo containerInfo = new ContainerInfo();
    List<ColumnInfo> columnList = new ArrayList<ColumnInfo>();
    columnList.add(new ColumnInfo("timestamp", GSType.TIMESTAMP));
    columnList.add(new ColumnInfo("value", GSType.FLOAT));
    containerInfo.setColumnInfoList(columnList);
    containerInfo.setRowKeyAssigned(true);

    TimeSeriesProperties tsProp = new TimeSeriesProperties();
    tsProp.setRowExpiration(1, TimeUnit.MINUTE);
    tsProp.setExpirationDivisionCount(5);
    containerInfo.setTimeSeriesProperties(tsProp);

    Properties props = new Properties();
    props.setProperty("host", "192.168.1.134");
    props.setProperty("port", "10001");
    props.setProperty("clusterName", "myCluster");
    props.setProperty("user", "admin");
    props.setProperty("password", "admin");
    props.setProperty("database","public");
    props.setProperty("transactionTimeout","5000");
    props.setProperty("failoverTimeout","5000");
    GridStore store = GridStoreFactory.getInstance().getGridStore(props);
    TimeSeries<Row> lctime1 = store.putTimeSeries("lctime", containerInfo, false);
    System.out.println("create");
    store.close();
```
Exception in thread "main" com.toshiba.mwcloud.gs.common.GSStatementException: [1007:CM_NOT_SUPPORTED] not support Row Expiration (address=192.168.1.134:10001, partitionId=10)

Location where the error occurred
```jsx
TimeSeries<Row> lctime1 = store.putTimeSeries("lctime", containerInfo, false);
```

How to solve this problem? thank you

**Comment by CCCpointer** [comment]
I had the same problem. when i choose the row expiration, it doesn't work.

Here is the official example: 

`CREATE TABLE myTimeseries (
  mycolumn1 TIMESTAMP PRIMARY KEY,
  mycolumn2 STRING
) USING TIMESERIES WITH (
  expiration_type='ROW',
  expiration_time=10,
  expiration_time_unit='DAY'
);`

**Comment by knonomura** [comment]
Row Expiration function has been discontinued in V5. 
Could you please use Partition Expiration function with JDBC driver (SQL interface) instead of it ?

https://github.com/griddb/griddb/blob/master/docs/GridDB-5.0-CE-RELEASE_NOTES.md

Example:
CREATE TABLE lctime ( 
  timestamp TIMESTAMP PRIMARY KEY, 
  value FLOAT 
) USING TIMESERIES WITH (
  expiration_type='PARTITION',
  expiration_time=60,
  expiration_time_unit='DAY'
) PARTITION BY RANGE (timestamp) EVERY (30, DAY); 

https://github.com/griddb/docs-en/blob/master/manuals/GridDB_FeaturesReference.md#expiry-release-function

**Comment by tom055** [comment]
Thank you very much for your reply.
